# Run algorithm on COVID data

In [1]:
import requests
import pandas as pd

In [33]:
url_switzerland = "https://lapis.cov-spectrum.org/gisaid/v2/sample/aggregated?country=Switzerland&dateFrom=2024-10-14&dateTo=2025-04-09&host=Human&accessKey=9Cb3CqmrFnVjO3XCxQLO6gUnKPd&fields=nextcladePangoLineage,date"
url_world = "https://lapis.cov-spectrum.org/gisaid/v2/sample/aggregated?&dateFrom=2024-10-14&dateTo=2025-04-09&host=Human&accessKey=9Cb3CqmrFnVjO3XCxQLO6gUnKPd&fields=nextcladePangoLineage,date,country"
url_usa = "https://lapis.cov-spectrum.org/gisaid/v2/sample/aggregated?country=USA&dateFrom=2024-10-14&dateTo=2025-04-16&host=Human&accessKey=9Cb3CqmrFnVjO3XCxQLO6gUnKPd&fields=nextcladePangoLineage,date"
response = requests.get(url_usa)

response.raise_for_status() # Raise an error if the request failed
data = response.json()  # Parse the JSON content
counts_df = pd.DataFrame(data['data'])

counts_df.head()

   count        date nextcladePangoLineage
0      1  2025-03-18                  BE.1
1      1  2025-03-18              BA.5.2.1
2      2  2025-01-31                 XEK.1
3      1  2025-03-02                 XEC.1
4      1  2025-02-28                XEC.19

In [34]:
counts_df = counts_df[counts_df.date < '2025-03-15']    # counts after this date have counts below 40

#possibly filter out variants with too less counts
#variant_counts = counts_df['nextcladePangoLineage'].value_counts()
#variants_to_keep = variant_counts[variant_counts >= 2].index
#counts_df = counts_df[counts_df['nextcladePangoLineage'].isin(variants_to_keep)]

In [15]:
counts_df.sort_values(by="date")

      count        date nextcladePangoLineage
757       1  2024-10-14                 MC.30
778       3  2024-10-14                LF.7.1
6848      1  2024-10-14                 MC.29
4006      1  2024-10-14              KP.3.2.6
6810      1  2024-10-14                 XEC.8
...     ...         ...                   ...
4824      1  2025-03-31              LF.7.7.2
6186      3  2025-04-01                LP.8.1
4846      2  2025-04-01              LP.8.1.1
3843      1  2025-04-02              LP.8.1.1
5631      1  2025-04-04                LP.8.1

[11294 rows x 3 columns]

In [29]:
counts_df["date"].value_counts().sort_index()

date
2024-10-14    90
2024-10-15    90
2024-10-16    72
2024-10-17    74
2024-10-18    59
              ..
2025-03-10    53
2025-03-11    58
2025-03-12    47
2025-03-13    58
2025-03-14    44
Name: count, Length: 152, dtype: int64

In [32]:
counts_df['nextcladePangoLineage'].value_counts()

nextcladePangoLineage
XEC         152
KP.3.1.1    149
MC.1        148
XEC.2       146
MC.10.1     145
           ...
MC.40.1       2
LB.1.5        2
XFA           2
MU.2          2
KP.2.10       2
Name: count, Length: 368, dtype: int64